version: '{build}'


environment:
  VERSION: 1.3.4
  TARGET_CONFIGURATION: Release

image: Visual Studio 2022
platform: Any CPU

branches:
  only:
    - master

only_commits:
  message: /(build|publish)/
#  files:
#    - src/*

before_build:
- cmd: >-
    dotnet --version

    dotnet restore

build_script:
- cmd: >-
    dotnet pack .\src\Doulex.DomainDriven -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

    dotnet pack .\src\Doulex.DomainDriven.Repo.EFCore -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

    dotnet pack .\src\Doulex.DomainDriven.Repo.FileSystem -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

artifacts:
  - path: "src/**/*.nupkg"
    name: "Doulex.DomainDriven NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: /1GFGVJM5rQof2MSnaX7nt36WRn0iH2LxApWOe+jP8Pr0YoJnmCjRWmBVrr2PxDL
    artifact: /.*\.nupkg/
