version: '{build}'

environment:
  VERSION: 1.6.3
  TARGET_CONFIGURATION: Release

image: 
  - Visual Studio 2022
  - Ubuntu

platform: 
  - Any CPU

branches:
  only:
    - master

only_commits:
  message: /(build|publish)/
#  files:
#    - src/*

before_build:
- cmd: >-
    dotnet --version

    dotnet restore

build_script:
- cmd: >-
    dotnet build Doulex.DomainDriven.sln -c %TARGET_CONFIGURATION%

    dotnet pack .\src\Doulex.DomainDriven -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

    dotnet pack .\src\Doulex.DomainDriven.Repo.EFCore -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

    dotnet pack .\src\Doulex.DomainDriven.Repo.FileSystem -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

artifacts:
  - path: "src/**/*.nupkg"
    name: "Doulex.DomainDriven NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: UIRvzyHvZdb41Gixu5+IJ9nrOhfuj7Ey9mU52bL/kJAUFBLZN+tPQR2eydBnEDAp
    artifact: /.*\.nupkg/
