version: '{build}'

environment:
  VERSION: 1.2.0
  TARGET_CONFIGURATION: Release

image: Visual Studio 2022
platform: Any CPU

branches:
  only:
    - master

only_commits:
  message: /(build|publish)/
#  files:
#    - src/*

before_build:
- cmd: >-
    dotnet --version

    dotnet restore

build_script:
- cmd: >-
    dotnet pack .\src\Doulex.DomainDriven -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

    dotnet pack .\src\Doulex.DomainDriven.Repo.EFCore -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION%

artifacts:
  - path: "src/**/*.nupkg"
    name: "Doulex.DomainDriven NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: oy2oslbxc47at7qxtz6q5pus47elgq5unjb2h2m34hivm4
    artifact: /.*\.nupkg/
